---
- name: Install puppet-agent on RHEL 7
  yum:
    name: puppetserver
    state: present
  when: ansible_os_family == "RedHat"

- name: Install puppet-agent on Debian
  apt:
    name: puppetserver
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
